name: Feature Request
description: Propose a new feature or improvement for a cofy-x repository.
title: "[Feature]: "
labels:
  - enhancement
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Describe the problem first, then propose your preferred solution.

  - type: input
    id: repository
    attributes:
      label: Target Repository
      description: Which cofy-x repository should this apply to?
      placeholder: "e.g., cofy-x/deck"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user or developer problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your preferred approach.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List other options and tradeoffs.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Links, mockups, references, or examples.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues for similar requests.
          required: true
